swagger:
  enabled: false
server:
  address: ":8090"
whatsmeow:
  autoMarkMessage: false
  db:
    dialect: "sqlite3"
    address: "file:whatsmeow.db?_foreign_keys=on"
  client:
    platform: "Linux"
    businessName: "Chrome"
    pushName: "faraway"
logger:
  logic:
    path: "./logs"           # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file: "logic_{Y-m}.log"        # 日志文件格式。默认为"{Y-m-d}.log"
    level: "prod"                 # 日志输出级别
    stdout: false                  # 日志是否同时输出到终端。默认true
    rotateSize: "50M"                     # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateExpire: "1d"                     # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit: 3                     # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire: "7d"                     # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  default:
    path:                  "./logs"           # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file:                  "{Y-m}.log"        # 日志文件格式。默认为"{Y-m-d}.log"
    level:                 "prod"                 # 日志输出级别
    stdout:                false                  # 日志是否同时输出到终端。默认true
    rotateSize:            "50M"                     # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateExpire:          "1d"                     # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit:     3                     # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire:    "7d"                     # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除